### PR TITLE
Configure build on appcenter

### PR DESCRIPTION
**Pull request by axolotl0212**

### CODE REVIEW

**Comment by axolotl0212** [comment]
rebased

**Review by louischan-oursky — COMMENTED** [review]
Is the keystore the real one for building the app? We should not commit credentials in public repositories!

**Comment by axolotl0212** [comment]
> Is the keystore the real one for building the app? We should not commit credentials in public repositories!

Yes, will remove the commit

**Comment by louischan-oursky** [comment]
In addition to removing the commit, we must regenerate a new one and use the new keystore to build the app.

**Comment by carmenlau** [comment]
The build is working already, add build badge in #55

**Pull request closed without merging**
